#!/usr/bin/python3.8


from easysnmp import Session

session  = Session(\
                hostname = '192.168.200.3',\
                version = 3,\
                security_level = 'auth_with_privacy',\
                security_username = 'cumulus',\
                auth_protocol = 'SHA',\
                auth_password = 'cumulus8password',\
                privacy_protocol = 'AES',\
                privacy_password = 'cumulus8encryption')

print("\n\tSNMP GET retrieved: "+session.get('1.3.6.1.2.1.1.5.0').value)
